[book]
authors = ["HQS Quantum Simulations", "Kirsten Bark", "Nicolas Vogt"]
language = "en"
multilingual = false
src = "src"
title = "HQS Struqture User Documentation"


[output.html]
mathjax-support = true