name: HQS CI tests for rust pyo3 repos

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  linting:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_rust_pyo3.yml@main

  unittests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
      # Run tests also on python 3.13
      python_3_13: true
      # Change this for each release!
      rust_package_name: "struqture@1.12.0"
      features: "json_schema indexed_map_iterators unstable_struqture_2_import"
      test_code_coverage: false

  build_tests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_tests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: true
      # Don't run tests on macos runners
      macos: true
      # Run tests also on python 3.13
      python_3_13: true
      py_interface_folder: "struqture-py"
      has_python_tests: true
