name: Manual user documentation and API documentation generation and upload

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.6.1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ./struqture-py/
        python -m pip install -r ./struqture-py/docs/requirements.txt
    - uses: peaceiris/actions-mdbook@v1
      with:
        version: latest
    - name: build
      run: |
        cd ./struqture-py/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./struqture-py/docs/_build/html documentation/src/pyapi
        mdbook build
        
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/book/
